# Generated by Django 5.2.9 on 2026-01-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
